<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: apache/rocketmq/v2/service.proto

namespace Apache\Rocketmq\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>apache.rocketmq.v2.QueryRouteResponse</code>
 */
class QueryRouteResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.apache.rocketmq.v2.Status status = 1;</code>
     */
    protected $status = null;
    /**
     * Generated from protobuf field <code>repeated .apache.rocketmq.v2.MessageQueue message_queues = 2;</code>
     */
    private $message_queues;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Apache\Rocketmq\V2\Status $status
     *     @type \Apache\Rocketmq\V2\MessageQueue[] $message_queues
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Apache\Rocketmq\V2\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.apache.rocketmq.v2.Status status = 1;</code>
     * @return \Apache\Rocketmq\V2\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * Generated from protobuf field <code>.apache.rocketmq.v2.Status status = 1;</code>
     * @param \Apache\Rocketmq\V2\Status $var
     * @return $this
     */
    public function setStatus(\Apache\Rocketmq\V2\Status|null $var)
    {
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .apache.rocketmq.v2.MessageQueue message_queues = 2;</code>
     * @return RepeatedField<\Apache\Rocketmq\V2\MessageQueue>
     */
    public function getMessageQueues()
    {
        return $this->message_queues;
    }

    /**
     * Generated from protobuf field <code>repeated .apache.rocketmq.v2.MessageQueue message_queues = 2;</code>
     * @param \Apache\Rocketmq\V2\MessageQueue[] $var
     * @return $this
     */
    public function setMessageQueues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Apache\Rocketmq\V2\MessageQueue::class);
        $this->message_queues = $arr;

        return $this;
    }

}

