// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v1/definition.proto

package apache.rocketmq.v1;

/**
 * Protobuf enum {@code apache.rocketmq.v1.ConsumePolicy}
 */
public enum ConsumePolicy
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>RESUME = 0;</code>
   */
  RESUME(0),
  /**
   * <code>PLAYBACK = 1;</code>
   */
  PLAYBACK(1),
  /**
   * <code>DISCARD = 2;</code>
   */
  DISCARD(2),
  /**
   * <code>TARGET_TIMESTAMP = 3;</code>
   */
  TARGET_TIMESTAMP(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>RESUME = 0;</code>
   */
  public static final int RESUME_VALUE = 0;
  /**
   * <code>PLAYBACK = 1;</code>
   */
  public static final int PLAYBACK_VALUE = 1;
  /**
   * <code>DISCARD = 2;</code>
   */
  public static final int DISCARD_VALUE = 2;
  /**
   * <code>TARGET_TIMESTAMP = 3;</code>
   */
  public static final int TARGET_TIMESTAMP_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ConsumePolicy valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ConsumePolicy forNumber(int value) {
    switch (value) {
      case 0: return RESUME;
      case 1: return PLAYBACK;
      case 2: return DISCARD;
      case 3: return TARGET_TIMESTAMP;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ConsumePolicy>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ConsumePolicy> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ConsumePolicy>() {
          public ConsumePolicy findValueByNumber(int number) {
            return ConsumePolicy.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return apache.rocketmq.v1.MQDomain.getDescriptor().getEnumTypes().get(3);
  }

  private static final ConsumePolicy[] VALUES = values();

  public static ConsumePolicy valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ConsumePolicy(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:apache.rocketmq.v1.ConsumePolicy)
}

