// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v1/service.proto

package apache.rocketmq.v1;

public interface EndTransactionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apache.rocketmq.v1.EndTransactionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.apache.rocketmq.v1.Resource group = 1;</code>
   * @return Whether the group field is set.
   */
  boolean hasGroup();
  /**
   * <code>.apache.rocketmq.v1.Resource group = 1;</code>
   * @return The group.
   */
  apache.rocketmq.v1.Resource getGroup();
  /**
   * <code>.apache.rocketmq.v1.Resource group = 1;</code>
   */
  apache.rocketmq.v1.ResourceOrBuilder getGroupOrBuilder();

  /**
   * <code>string message_id = 2;</code>
   * @return The messageId.
   */
  java.lang.String getMessageId();
  /**
   * <code>string message_id = 2;</code>
   * @return The bytes for messageId.
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();

  /**
   * <code>string transaction_id = 3;</code>
   * @return The transactionId.
   */
  java.lang.String getTransactionId();
  /**
   * <code>string transaction_id = 3;</code>
   * @return The bytes for transactionId.
   */
  com.google.protobuf.ByteString
      getTransactionIdBytes();

  /**
   * <code>.apache.rocketmq.v1.EndTransactionRequest.TransactionResolution resolution = 4;</code>
   * @return The enum numeric value on the wire for resolution.
   */
  int getResolutionValue();
  /**
   * <code>.apache.rocketmq.v1.EndTransactionRequest.TransactionResolution resolution = 4;</code>
   * @return The resolution.
   */
  apache.rocketmq.v1.EndTransactionRequest.TransactionResolution getResolution();

  /**
   * <code>.apache.rocketmq.v1.EndTransactionRequest.Source source = 5;</code>
   * @return The enum numeric value on the wire for source.
   */
  int getSourceValue();
  /**
   * <code>.apache.rocketmq.v1.EndTransactionRequest.Source source = 5;</code>
   * @return The source.
   */
  apache.rocketmq.v1.EndTransactionRequest.Source getSource();

  /**
   * <code>string trace_context = 6;</code>
   * @return The traceContext.
   */
  java.lang.String getTraceContext();
  /**
   * <code>string trace_context = 6;</code>
   * @return The bytes for traceContext.
   */
  com.google.protobuf.ByteString
      getTraceContextBytes();
}
