// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v1/service.proto

package apache.rocketmq.v1;

public interface HeartbeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apache.rocketmq.v1.HeartbeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .apache.rocketmq.v1.HeartbeatEntry heartbeats = 1;</code>
   */
  java.util.List<apache.rocketmq.v1.HeartbeatEntry> 
      getHeartbeatsList();
  /**
   * <code>repeated .apache.rocketmq.v1.HeartbeatEntry heartbeats = 1;</code>
   */
  apache.rocketmq.v1.HeartbeatEntry getHeartbeats(int index);
  /**
   * <code>repeated .apache.rocketmq.v1.HeartbeatEntry heartbeats = 1;</code>
   */
  int getHeartbeatsCount();
  /**
   * <code>repeated .apache.rocketmq.v1.HeartbeatEntry heartbeats = 1;</code>
   */
  java.util.List<? extends apache.rocketmq.v1.HeartbeatEntryOrBuilder> 
      getHeartbeatsOrBuilderList();
  /**
   * <code>repeated .apache.rocketmq.v1.HeartbeatEntry heartbeats = 1;</code>
   */
  apache.rocketmq.v1.HeartbeatEntryOrBuilder getHeartbeatsOrBuilder(
      int index);
}
