// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v1/definition.proto

package apache.rocketmq.v1;

/**
 * Protobuf type {@code apache.rocketmq.v1.HeartbeatEntry}
 */
public final class HeartbeatEntry extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:apache.rocketmq.v1.HeartbeatEntry)
    HeartbeatEntryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HeartbeatEntry.newBuilder() to construct.
  private HeartbeatEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HeartbeatEntry() {
    clientId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HeartbeatEntry();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HeartbeatEntry(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            clientId_ = s;
            break;
          }
          case 18: {
            apache.rocketmq.v1.ProducerGroup.Builder subBuilder = null;
            if (clientDataCase_ == 2) {
              subBuilder = ((apache.rocketmq.v1.ProducerGroup) clientData_).toBuilder();
            }
            clientData_ =
                input.readMessage(apache.rocketmq.v1.ProducerGroup.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((apache.rocketmq.v1.ProducerGroup) clientData_);
              clientData_ = subBuilder.buildPartial();
            }
            clientDataCase_ = 2;
            break;
          }
          case 26: {
            apache.rocketmq.v1.ConsumerGroup.Builder subBuilder = null;
            if (clientDataCase_ == 3) {
              subBuilder = ((apache.rocketmq.v1.ConsumerGroup) clientData_).toBuilder();
            }
            clientData_ =
                input.readMessage(apache.rocketmq.v1.ConsumerGroup.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((apache.rocketmq.v1.ConsumerGroup) clientData_);
              clientData_ = subBuilder.buildPartial();
            }
            clientDataCase_ = 3;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return apache.rocketmq.v1.MQDomain.internal_static_apache_rocketmq_v1_HeartbeatEntry_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return apache.rocketmq.v1.MQDomain.internal_static_apache_rocketmq_v1_HeartbeatEntry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            apache.rocketmq.v1.HeartbeatEntry.class, apache.rocketmq.v1.HeartbeatEntry.Builder.class);
  }

  private int clientDataCase_ = 0;
  private java.lang.Object clientData_;
  public enum ClientDataCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    PRODUCER_GROUP(2),
    CONSUMER_GROUP(3),
    CLIENTDATA_NOT_SET(0);
    private final int value;
    private ClientDataCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ClientDataCase valueOf(int value) {
      return forNumber(value);
    }

    public static ClientDataCase forNumber(int value) {
      switch (value) {
        case 2: return PRODUCER_GROUP;
        case 3: return CONSUMER_GROUP;
        case 0: return CLIENTDATA_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ClientDataCase
  getClientDataCase() {
    return ClientDataCase.forNumber(
        clientDataCase_);
  }

  public static final int CLIENT_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object clientId_;
  /**
   * <code>string client_id = 1;</code>
   * @return The clientId.
   */
  @java.lang.Override
  public java.lang.String getClientId() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientId_ = s;
      return s;
    }
  }
  /**
   * <code>string client_id = 1;</code>
   * @return The bytes for clientId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientIdBytes() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCER_GROUP_FIELD_NUMBER = 2;
  /**
   * <code>.apache.rocketmq.v1.ProducerGroup producer_group = 2;</code>
   * @return Whether the producerGroup field is set.
   */
  @java.lang.Override
  public boolean hasProducerGroup() {
    return clientDataCase_ == 2;
  }
  /**
   * <code>.apache.rocketmq.v1.ProducerGroup producer_group = 2;</code>
   * @return The producerGroup.
   */
  @java.lang.Override
  public apache.rocketmq.v1.ProducerGroup getProducerGroup() {
    if (clientDataCase_ == 2) {
       return (apache.rocketmq.v1.ProducerGroup) clientData_;
    }
    return apache.rocketmq.v1.ProducerGroup.getDefaultInstance();
  }
  /**
   * <code>.apache.rocketmq.v1.ProducerGroup producer_group = 2;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v1.ProducerGroupOrBuilder getProducerGroupOrBuilder() {
    if (clientDataCase_ == 2) {
       return (apache.rocketmq.v1.ProducerGroup) clientData_;
    }
    return apache.rocketmq.v1.ProducerGroup.getDefaultInstance();
  }

  public static final int CONSUMER_GROUP_FIELD_NUMBER = 3;
  /**
   * <code>.apache.rocketmq.v1.ConsumerGroup consumer_group = 3;</code>
   * @return Whether the consumerGroup field is set.
   */
  @java.lang.Override
  public boolean hasConsumerGroup() {
    return clientDataCase_ == 3;
  }
  /**
   * <code>.apache.rocketmq.v1.ConsumerGroup consumer_group = 3;</code>
   * @return The consumerGroup.
   */
  @java.lang.Override
  public apache.rocketmq.v1.ConsumerGroup getConsumerGroup() {
    if (clientDataCase_ == 3) {
       return (apache.rocketmq.v1.ConsumerGroup) clientData_;
    }
    return apache.rocketmq.v1.ConsumerGroup.getDefaultInstance();
  }
  /**
   * <code>.apache.rocketmq.v1.ConsumerGroup consumer_group = 3;</code>
   */
  @java.lang.Override
  public apache.rocketmq.v1.ConsumerGroupOrBuilder getConsumerGroupOrBuilder() {
    if (clientDataCase_ == 3) {
       return (apache.rocketmq.v1.ConsumerGroup) clientData_;
    }
    return apache.rocketmq.v1.ConsumerGroup.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getClientIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientId_);
    }
    if (clientDataCase_ == 2) {
      output.writeMessage(2, (apache.rocketmq.v1.ProducerGroup) clientData_);
    }
    if (clientDataCase_ == 3) {
      output.writeMessage(3, (apache.rocketmq.v1.ConsumerGroup) clientData_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getClientIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientId_);
    }
    if (clientDataCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (apache.rocketmq.v1.ProducerGroup) clientData_);
    }
    if (clientDataCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (apache.rocketmq.v1.ConsumerGroup) clientData_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof apache.rocketmq.v1.HeartbeatEntry)) {
      return super.equals(obj);
    }
    apache.rocketmq.v1.HeartbeatEntry other = (apache.rocketmq.v1.HeartbeatEntry) obj;

    if (!getClientId()
        .equals(other.getClientId())) return false;
    if (!getClientDataCase().equals(other.getClientDataCase())) return false;
    switch (clientDataCase_) {
      case 2:
        if (!getProducerGroup()
            .equals(other.getProducerGroup())) return false;
        break;
      case 3:
        if (!getConsumerGroup()
            .equals(other.getConsumerGroup())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLIENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getClientId().hashCode();
    switch (clientDataCase_) {
      case 2:
        hash = (37 * hash) + PRODUCER_GROUP_FIELD_NUMBER;
        hash = (53 * hash) + getProducerGroup().hashCode();
        break;
      case 3:
        hash = (37 * hash) + CONSUMER_GROUP_FIELD_NUMBER;
        hash = (53 * hash) + getConsumerGroup().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static apache.rocketmq.v1.HeartbeatEntry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v1.HeartbeatEntry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v1.HeartbeatEntry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v1.HeartbeatEntry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v1.HeartbeatEntry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static apache.rocketmq.v1.HeartbeatEntry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static apache.rocketmq.v1.HeartbeatEntry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v1.HeartbeatEntry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static apache.rocketmq.v1.HeartbeatEntry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v1.HeartbeatEntry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static apache.rocketmq.v1.HeartbeatEntry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static apache.rocketmq.v1.HeartbeatEntry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(apache.rocketmq.v1.HeartbeatEntry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code apache.rocketmq.v1.HeartbeatEntry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:apache.rocketmq.v1.HeartbeatEntry)
      apache.rocketmq.v1.HeartbeatEntryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return apache.rocketmq.v1.MQDomain.internal_static_apache_rocketmq_v1_HeartbeatEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return apache.rocketmq.v1.MQDomain.internal_static_apache_rocketmq_v1_HeartbeatEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              apache.rocketmq.v1.HeartbeatEntry.class, apache.rocketmq.v1.HeartbeatEntry.Builder.class);
    }

    // Construct using apache.rocketmq.v1.HeartbeatEntry.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      clientId_ = "";

      clientDataCase_ = 0;
      clientData_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return apache.rocketmq.v1.MQDomain.internal_static_apache_rocketmq_v1_HeartbeatEntry_descriptor;
    }

    @java.lang.Override
    public apache.rocketmq.v1.HeartbeatEntry getDefaultInstanceForType() {
      return apache.rocketmq.v1.HeartbeatEntry.getDefaultInstance();
    }

    @java.lang.Override
    public apache.rocketmq.v1.HeartbeatEntry build() {
      apache.rocketmq.v1.HeartbeatEntry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public apache.rocketmq.v1.HeartbeatEntry buildPartial() {
      apache.rocketmq.v1.HeartbeatEntry result = new apache.rocketmq.v1.HeartbeatEntry(this);
      result.clientId_ = clientId_;
      if (clientDataCase_ == 2) {
        if (producerGroupBuilder_ == null) {
          result.clientData_ = clientData_;
        } else {
          result.clientData_ = producerGroupBuilder_.build();
        }
      }
      if (clientDataCase_ == 3) {
        if (consumerGroupBuilder_ == null) {
          result.clientData_ = clientData_;
        } else {
          result.clientData_ = consumerGroupBuilder_.build();
        }
      }
      result.clientDataCase_ = clientDataCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof apache.rocketmq.v1.HeartbeatEntry) {
        return mergeFrom((apache.rocketmq.v1.HeartbeatEntry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(apache.rocketmq.v1.HeartbeatEntry other) {
      if (other == apache.rocketmq.v1.HeartbeatEntry.getDefaultInstance()) return this;
      if (!other.getClientId().isEmpty()) {
        clientId_ = other.clientId_;
        onChanged();
      }
      switch (other.getClientDataCase()) {
        case PRODUCER_GROUP: {
          mergeProducerGroup(other.getProducerGroup());
          break;
        }
        case CONSUMER_GROUP: {
          mergeConsumerGroup(other.getConsumerGroup());
          break;
        }
        case CLIENTDATA_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      apache.rocketmq.v1.HeartbeatEntry parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (apache.rocketmq.v1.HeartbeatEntry) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int clientDataCase_ = 0;
    private java.lang.Object clientData_;
    public ClientDataCase
        getClientDataCase() {
      return ClientDataCase.forNumber(
          clientDataCase_);
    }

    public Builder clearClientData() {
      clientDataCase_ = 0;
      clientData_ = null;
      onChanged();
      return this;
    }


    private java.lang.Object clientId_ = "";
    /**
     * <code>string client_id = 1;</code>
     * @return The clientId.
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string client_id = 1;</code>
     * @return The bytes for clientId.
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string client_id = 1;</code>
     * @param value The clientId to set.
     * @return This builder for chaining.
     */
    public Builder setClientId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string client_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientId() {
      
      clientId_ = getDefaultInstance().getClientId();
      onChanged();
      return this;
    }
    /**
     * <code>string client_id = 1;</code>
     * @param value The bytes for clientId to set.
     * @return This builder for chaining.
     */
    public Builder setClientIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v1.ProducerGroup, apache.rocketmq.v1.ProducerGroup.Builder, apache.rocketmq.v1.ProducerGroupOrBuilder> producerGroupBuilder_;
    /**
     * <code>.apache.rocketmq.v1.ProducerGroup producer_group = 2;</code>
     * @return Whether the producerGroup field is set.
     */
    @java.lang.Override
    public boolean hasProducerGroup() {
      return clientDataCase_ == 2;
    }
    /**
     * <code>.apache.rocketmq.v1.ProducerGroup producer_group = 2;</code>
     * @return The producerGroup.
     */
    @java.lang.Override
    public apache.rocketmq.v1.ProducerGroup getProducerGroup() {
      if (producerGroupBuilder_ == null) {
        if (clientDataCase_ == 2) {
          return (apache.rocketmq.v1.ProducerGroup) clientData_;
        }
        return apache.rocketmq.v1.ProducerGroup.getDefaultInstance();
      } else {
        if (clientDataCase_ == 2) {
          return producerGroupBuilder_.getMessage();
        }
        return apache.rocketmq.v1.ProducerGroup.getDefaultInstance();
      }
    }
    /**
     * <code>.apache.rocketmq.v1.ProducerGroup producer_group = 2;</code>
     */
    public Builder setProducerGroup(apache.rocketmq.v1.ProducerGroup value) {
      if (producerGroupBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        clientData_ = value;
        onChanged();
      } else {
        producerGroupBuilder_.setMessage(value);
      }
      clientDataCase_ = 2;
      return this;
    }
    /**
     * <code>.apache.rocketmq.v1.ProducerGroup producer_group = 2;</code>
     */
    public Builder setProducerGroup(
        apache.rocketmq.v1.ProducerGroup.Builder builderForValue) {
      if (producerGroupBuilder_ == null) {
        clientData_ = builderForValue.build();
        onChanged();
      } else {
        producerGroupBuilder_.setMessage(builderForValue.build());
      }
      clientDataCase_ = 2;
      return this;
    }
    /**
     * <code>.apache.rocketmq.v1.ProducerGroup producer_group = 2;</code>
     */
    public Builder mergeProducerGroup(apache.rocketmq.v1.ProducerGroup value) {
      if (producerGroupBuilder_ == null) {
        if (clientDataCase_ == 2 &&
            clientData_ != apache.rocketmq.v1.ProducerGroup.getDefaultInstance()) {
          clientData_ = apache.rocketmq.v1.ProducerGroup.newBuilder((apache.rocketmq.v1.ProducerGroup) clientData_)
              .mergeFrom(value).buildPartial();
        } else {
          clientData_ = value;
        }
        onChanged();
      } else {
        if (clientDataCase_ == 2) {
          producerGroupBuilder_.mergeFrom(value);
        }
        producerGroupBuilder_.setMessage(value);
      }
      clientDataCase_ = 2;
      return this;
    }
    /**
     * <code>.apache.rocketmq.v1.ProducerGroup producer_group = 2;</code>
     */
    public Builder clearProducerGroup() {
      if (producerGroupBuilder_ == null) {
        if (clientDataCase_ == 2) {
          clientDataCase_ = 0;
          clientData_ = null;
          onChanged();
        }
      } else {
        if (clientDataCase_ == 2) {
          clientDataCase_ = 0;
          clientData_ = null;
        }
        producerGroupBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.apache.rocketmq.v1.ProducerGroup producer_group = 2;</code>
     */
    public apache.rocketmq.v1.ProducerGroup.Builder getProducerGroupBuilder() {
      return getProducerGroupFieldBuilder().getBuilder();
    }
    /**
     * <code>.apache.rocketmq.v1.ProducerGroup producer_group = 2;</code>
     */
    @java.lang.Override
    public apache.rocketmq.v1.ProducerGroupOrBuilder getProducerGroupOrBuilder() {
      if ((clientDataCase_ == 2) && (producerGroupBuilder_ != null)) {
        return producerGroupBuilder_.getMessageOrBuilder();
      } else {
        if (clientDataCase_ == 2) {
          return (apache.rocketmq.v1.ProducerGroup) clientData_;
        }
        return apache.rocketmq.v1.ProducerGroup.getDefaultInstance();
      }
    }
    /**
     * <code>.apache.rocketmq.v1.ProducerGroup producer_group = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v1.ProducerGroup, apache.rocketmq.v1.ProducerGroup.Builder, apache.rocketmq.v1.ProducerGroupOrBuilder> 
        getProducerGroupFieldBuilder() {
      if (producerGroupBuilder_ == null) {
        if (!(clientDataCase_ == 2)) {
          clientData_ = apache.rocketmq.v1.ProducerGroup.getDefaultInstance();
        }
        producerGroupBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            apache.rocketmq.v1.ProducerGroup, apache.rocketmq.v1.ProducerGroup.Builder, apache.rocketmq.v1.ProducerGroupOrBuilder>(
                (apache.rocketmq.v1.ProducerGroup) clientData_,
                getParentForChildren(),
                isClean());
        clientData_ = null;
      }
      clientDataCase_ = 2;
      onChanged();;
      return producerGroupBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v1.ConsumerGroup, apache.rocketmq.v1.ConsumerGroup.Builder, apache.rocketmq.v1.ConsumerGroupOrBuilder> consumerGroupBuilder_;
    /**
     * <code>.apache.rocketmq.v1.ConsumerGroup consumer_group = 3;</code>
     * @return Whether the consumerGroup field is set.
     */
    @java.lang.Override
    public boolean hasConsumerGroup() {
      return clientDataCase_ == 3;
    }
    /**
     * <code>.apache.rocketmq.v1.ConsumerGroup consumer_group = 3;</code>
     * @return The consumerGroup.
     */
    @java.lang.Override
    public apache.rocketmq.v1.ConsumerGroup getConsumerGroup() {
      if (consumerGroupBuilder_ == null) {
        if (clientDataCase_ == 3) {
          return (apache.rocketmq.v1.ConsumerGroup) clientData_;
        }
        return apache.rocketmq.v1.ConsumerGroup.getDefaultInstance();
      } else {
        if (clientDataCase_ == 3) {
          return consumerGroupBuilder_.getMessage();
        }
        return apache.rocketmq.v1.ConsumerGroup.getDefaultInstance();
      }
    }
    /**
     * <code>.apache.rocketmq.v1.ConsumerGroup consumer_group = 3;</code>
     */
    public Builder setConsumerGroup(apache.rocketmq.v1.ConsumerGroup value) {
      if (consumerGroupBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        clientData_ = value;
        onChanged();
      } else {
        consumerGroupBuilder_.setMessage(value);
      }
      clientDataCase_ = 3;
      return this;
    }
    /**
     * <code>.apache.rocketmq.v1.ConsumerGroup consumer_group = 3;</code>
     */
    public Builder setConsumerGroup(
        apache.rocketmq.v1.ConsumerGroup.Builder builderForValue) {
      if (consumerGroupBuilder_ == null) {
        clientData_ = builderForValue.build();
        onChanged();
      } else {
        consumerGroupBuilder_.setMessage(builderForValue.build());
      }
      clientDataCase_ = 3;
      return this;
    }
    /**
     * <code>.apache.rocketmq.v1.ConsumerGroup consumer_group = 3;</code>
     */
    public Builder mergeConsumerGroup(apache.rocketmq.v1.ConsumerGroup value) {
      if (consumerGroupBuilder_ == null) {
        if (clientDataCase_ == 3 &&
            clientData_ != apache.rocketmq.v1.ConsumerGroup.getDefaultInstance()) {
          clientData_ = apache.rocketmq.v1.ConsumerGroup.newBuilder((apache.rocketmq.v1.ConsumerGroup) clientData_)
              .mergeFrom(value).buildPartial();
        } else {
          clientData_ = value;
        }
        onChanged();
      } else {
        if (clientDataCase_ == 3) {
          consumerGroupBuilder_.mergeFrom(value);
        }
        consumerGroupBuilder_.setMessage(value);
      }
      clientDataCase_ = 3;
      return this;
    }
    /**
     * <code>.apache.rocketmq.v1.ConsumerGroup consumer_group = 3;</code>
     */
    public Builder clearConsumerGroup() {
      if (consumerGroupBuilder_ == null) {
        if (clientDataCase_ == 3) {
          clientDataCase_ = 0;
          clientData_ = null;
          onChanged();
        }
      } else {
        if (clientDataCase_ == 3) {
          clientDataCase_ = 0;
          clientData_ = null;
        }
        consumerGroupBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.apache.rocketmq.v1.ConsumerGroup consumer_group = 3;</code>
     */
    public apache.rocketmq.v1.ConsumerGroup.Builder getConsumerGroupBuilder() {
      return getConsumerGroupFieldBuilder().getBuilder();
    }
    /**
     * <code>.apache.rocketmq.v1.ConsumerGroup consumer_group = 3;</code>
     */
    @java.lang.Override
    public apache.rocketmq.v1.ConsumerGroupOrBuilder getConsumerGroupOrBuilder() {
      if ((clientDataCase_ == 3) && (consumerGroupBuilder_ != null)) {
        return consumerGroupBuilder_.getMessageOrBuilder();
      } else {
        if (clientDataCase_ == 3) {
          return (apache.rocketmq.v1.ConsumerGroup) clientData_;
        }
        return apache.rocketmq.v1.ConsumerGroup.getDefaultInstance();
      }
    }
    /**
     * <code>.apache.rocketmq.v1.ConsumerGroup consumer_group = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        apache.rocketmq.v1.ConsumerGroup, apache.rocketmq.v1.ConsumerGroup.Builder, apache.rocketmq.v1.ConsumerGroupOrBuilder> 
        getConsumerGroupFieldBuilder() {
      if (consumerGroupBuilder_ == null) {
        if (!(clientDataCase_ == 3)) {
          clientData_ = apache.rocketmq.v1.ConsumerGroup.getDefaultInstance();
        }
        consumerGroupBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            apache.rocketmq.v1.ConsumerGroup, apache.rocketmq.v1.ConsumerGroup.Builder, apache.rocketmq.v1.ConsumerGroupOrBuilder>(
                (apache.rocketmq.v1.ConsumerGroup) clientData_,
                getParentForChildren(),
                isClean());
        clientData_ = null;
      }
      clientDataCase_ = 3;
      onChanged();;
      return consumerGroupBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:apache.rocketmq.v1.HeartbeatEntry)
  }

  // @@protoc_insertion_point(class_scope:apache.rocketmq.v1.HeartbeatEntry)
  private static final apache.rocketmq.v1.HeartbeatEntry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new apache.rocketmq.v1.HeartbeatEntry();
  }

  public static apache.rocketmq.v1.HeartbeatEntry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HeartbeatEntry>
      PARSER = new com.google.protobuf.AbstractParser<HeartbeatEntry>() {
    @java.lang.Override
    public HeartbeatEntry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HeartbeatEntry(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HeartbeatEntry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HeartbeatEntry> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public apache.rocketmq.v1.HeartbeatEntry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

