// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v1/service.proto

package apache.rocketmq.v1;

public final class MQService {
  private MQService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_ResponseCommon_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_ResponseCommon_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_QueryRouteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_QueryRouteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_QueryRouteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_QueryRouteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_SendMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_SendMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_SendMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_SendMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_QueryAssignmentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_QueryAssignmentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_QueryAssignmentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_QueryAssignmentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_ReceiveMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_ReceiveMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_ReceiveMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_ReceiveMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_AckMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_AckMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_AckMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_AckMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_NackMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_NackMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_NackMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_NackMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_ForwardMessageToDeadLetterQueueRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_ForwardMessageToDeadLetterQueueRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_ForwardMessageToDeadLetterQueueResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_ForwardMessageToDeadLetterQueueResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_HeartbeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_HealthCheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_HealthCheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_HealthCheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_HealthCheckResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_EndTransactionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_EndTransactionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_EndTransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_EndTransactionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_QueryOffsetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_QueryOffsetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_QueryOffsetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_QueryOffsetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_PullMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_PullMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_PullMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_PullMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_UpdateOffsetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_UpdateOffsetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_UpdateOffsetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_UpdateOffsetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_GenericPollingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_GenericPollingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_GenericPollingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_GenericPollingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_PrintThreadStackRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_PrintThreadStackRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_PrintThreadStackResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_PrintThreadStackResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_VerifyMessageConsumptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_VerifyMessageConsumptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_VerifyMessageConsumptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_VerifyMessageConsumptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_RecoverOrphanedTransactionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_RecoverOrphanedTransactionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_MultiplexingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_MultiplexingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_MultiplexingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_MultiplexingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_NotifyClientTerminationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_NotifyClientTerminationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apache_rocketmq_v1_NotifyClientTerminationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apache_rocketmq_v1_NotifyClientTerminationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n apache/rocketmq/v1/service.proto\022\022apac" +
      "he.rocketmq.v1\032\031google/protobuf/any.prot" +
      "o\032\036google/protobuf/duration.proto\032\037googl" +
      "e/protobuf/timestamp.proto\032\036google/rpc/e" +
      "rror_details.proto\032\025google/rpc/code.prot" +
      "o\032\027google/rpc/status.proto\032#apache/rocke" +
      "tmq/v1/definition.proto\"\204\002\n\016ResponseComm" +
      "on\022\"\n\006status\030\001 \001(\0132\022.google.rpc.Status\022-" +
      "\n\014request_info\030\002 \001(\0132\027.google.rpc.Reques" +
      "tInfo\022\036\n\004help\030\003 \001(\0132\020.google.rpc.Help\022)\n" +
      "\nretry_info\030\004 \001(\0132\025.google.rpc.RetryInfo" +
      "\022)\n\ndebug_info\030\005 \001(\0132\025.google.rpc.DebugI" +
      "nfo\022)\n\nerror_info\030\006 \001(\0132\025.google.rpc.Err" +
      "orInfo\"r\n\021QueryRouteRequest\022+\n\005topic\030\001 \001" +
      "(\0132\034.apache.rocketmq.v1.Resource\0220\n\tendp" +
      "oints\030\002 \001(\0132\035.apache.rocketmq.v1.Endpoin" +
      "ts\"{\n\022QueryRouteResponse\0222\n\006common\030\001 \001(\013" +
      "2\".apache.rocketmq.v1.ResponseCommon\0221\n\n" +
      "partitions\030\002 \003(\0132\035.apache.rocketmq.v1.Pa" +
      "rtition\"t\n\022SendMessageRequest\022,\n\007message" +
      "\030\001 \001(\0132\033.apache.rocketmq.v1.Message\0220\n\tp" +
      "artition\030\002 \001(\0132\035.apache.rocketmq.v1.Part" +
      "ition\"u\n\023SendMessageResponse\0222\n\006common\030\001" +
      " \001(\0132\".apache.rocketmq.v1.ResponseCommon" +
      "\022\022\n\nmessage_id\030\002 \001(\t\022\026\n\016transaction_id\030\003" +
      " \001(\t\"\267\001\n\026QueryAssignmentRequest\022+\n\005topic" +
      "\030\001 \001(\0132\034.apache.rocketmq.v1.Resource\022+\n\005" +
      "group\030\002 \001(\0132\034.apache.rocketmq.v1.Resourc" +
      "e\022\021\n\tclient_id\030\003 \001(\t\0220\n\tendpoints\030\004 \001(\0132" +
      "\035.apache.rocketmq.v1.Endpoints\"\202\001\n\027Query" +
      "AssignmentResponse\0222\n\006common\030\001 \001(\0132\".apa" +
      "che.rocketmq.v1.ResponseCommon\0223\n\013assign" +
      "ments\030\002 \003(\0132\036.apache.rocketmq.v1.Assignm" +
      "ent\"\320\003\n\025ReceiveMessageRequest\022+\n\005group\030\001" +
      " \001(\0132\034.apache.rocketmq.v1.Resource\022\021\n\tcl" +
      "ient_id\030\002 \001(\t\0220\n\tpartition\030\003 \001(\0132\035.apach" +
      "e.rocketmq.v1.Partition\022?\n\021filter_expres" +
      "sion\030\004 \001(\0132$.apache.rocketmq.v1.FilterEx" +
      "pression\0229\n\016consume_policy\030\005 \001(\0162!.apach" +
      "e.rocketmq.v1.ConsumePolicy\022<\n\030initializ" +
      "ation_timestamp\030\006 \001(\0132\032.google.protobuf." +
      "Timestamp\022\022\n\nbatch_size\030\007 \001(\005\0225\n\022invisib" +
      "le_duration\030\010 \001(\0132\031.google.protobuf.Dura" +
      "tion\022-\n\nawait_time\030\t \001(\0132\031.google.protob" +
      "uf.Duration\022\021\n\tfifo_flag\030\n \001(\010\"\352\001\n\026Recei" +
      "veMessageResponse\0222\n\006common\030\001 \001(\0132\".apac" +
      "he.rocketmq.v1.ResponseCommon\022-\n\010message" +
      "s\030\002 \003(\0132\033.apache.rocketmq.v1.Message\0226\n\022" +
      "delivery_timestamp\030\003 \001(\0132\032.google.protob" +
      "uf.Timestamp\0225\n\022invisible_duration\030\004 \001(\013" +
      "2\031.google.protobuf.Duration\"\312\001\n\021AckMessa" +
      "geRequest\022+\n\005group\030\001 \001(\0132\034.apache.rocket" +
      "mq.v1.Resource\022+\n\005topic\030\002 \001(\0132\034.apache.r" +
      "ocketmq.v1.Resource\022\021\n\tclient_id\030\003 \001(\t\022\030" +
      "\n\016receipt_handle\030\004 \001(\tH\000\022\020\n\006offset\030\005 \001(\003" +
      "H\000\022\022\n\nmessage_id\030\006 \001(\tB\010\n\006handle\"H\n\022AckM" +
      "essageResponse\0222\n\006common\030\001 \001(\0132\".apache." +
      "rocketmq.v1.ResponseCommon\"\346\001\n\022NackMessa" +
      "geRequest\022+\n\005group\030\001 \001(\0132\034.apache.rocket" +
      "mq.v1.Resource\022+\n\005topic\030\002 \001(\0132\034.apache.r" +
      "ocketmq.v1.Resource\022\021\n\tclient_id\030\003 \001(\t\022\026" +
      "\n\016receipt_handle\030\004 \001(\t\022\022\n\nmessage_id\030\005 \001" +
      "(\t\022\030\n\020delivery_attempt\030\006 \001(\005\022\035\n\025max_deli" +
      "very_attempts\030\007 \001(\005\"I\n\023NackMessageRespon" +
      "se\0222\n\006common\030\001 \001(\0132\".apache.rocketmq.v1." +
      "ResponseCommon\"\372\001\n&ForwardMessageToDeadL" +
      "etterQueueRequest\022+\n\005group\030\001 \001(\0132\034.apach" +
      "e.rocketmq.v1.Resource\022+\n\005topic\030\002 \001(\0132\034." +
      "apache.rocketmq.v1.Resource\022\021\n\tclient_id" +
      "\030\003 \001(\t\022\026\n\016receipt_handle\030\004 \001(\t\022\022\n\nmessag" +
      "e_id\030\005 \001(\t\022\030\n\020delivery_attempt\030\006 \001(\005\022\035\n\025" +
      "max_delivery_attempts\030\007 \001(\005\"]\n\'ForwardMe" +
      "ssageToDeadLetterQueueResponse\0222\n\006common" +
      "\030\001 \001(\0132\".apache.rocketmq.v1.ResponseComm" +
      "on\"\275\001\n\020HeartbeatRequest\022\021\n\tclient_id\030\001 \001" +
      "(\t\0229\n\rproducer_data\030\002 \001(\0132 .apache.rocke" +
      "tmq.v1.ProducerDataH\000\0229\n\rconsumer_data\030\003" +
      " \001(\0132 .apache.rocketmq.v1.ConsumerDataH\000" +
      "\022\021\n\tfifo_flag\030\004 \001(\010B\r\n\013client_data\"G\n\021He" +
      "artbeatResponse\0222\n\006common\030\001 \001(\0132\".apache" +
      ".rocketmq.v1.ResponseCommon\"V\n\022HealthChe" +
      "ckRequest\022+\n\005group\030\001 \001(\0132\034.apache.rocket" +
      "mq.v1.Resource\022\023\n\013client_host\030\002 \001(\t\"I\n\023H" +
      "ealthCheckResponse\0222\n\006common\030\001 \001(\0132\".apa" +
      "che.rocketmq.v1.ResponseCommon\"\371\002\n\025EndTr" +
      "ansactionRequest\022+\n\005group\030\001 \001(\0132\034.apache" +
      ".rocketmq.v1.Resource\022\022\n\nmessage_id\030\002 \001(" +
      "\t\022\026\n\016transaction_id\030\003 \001(\t\022S\n\nresolution\030" +
      "\004 \001(\0162?.apache.rocketmq.v1.EndTransactio" +
      "nRequest.TransactionResolution\022@\n\006source" +
      "\030\005 \001(\01620.apache.rocketmq.v1.EndTransacti" +
      "onRequest.Source\022\025\n\rtrace_context\030\006 \001(\t\"" +
      "1\n\025TransactionResolution\022\n\n\006COMMIT\020\000\022\014\n\010" +
      "ROLLBACK\020\001\"&\n\006Source\022\n\n\006CLIENT\020\000\022\020\n\014SERV" +
      "ER_CHECK\020\001\"L\n\026EndTransactionResponse\0222\n\006" +
      "common\030\001 \001(\0132\".apache.rocketmq.v1.Respon" +
      "seCommon\"\255\001\n\022QueryOffsetRequest\0220\n\tparti" +
      "tion\030\001 \001(\0132\035.apache.rocketmq.v1.Partitio" +
      "n\0225\n\006policy\030\002 \001(\0162%.apache.rocketmq.v1.Q" +
      "ueryOffsetPolicy\022.\n\ntime_point\030\003 \001(\0132\032.g" +
      "oogle.protobuf.Timestamp\"Y\n\023QueryOffsetR" +
      "esponse\0222\n\006common\030\001 \001(\0132\".apache.rocketm" +
      "q.v1.ResponseCommon\022\016\n\006offset\030\002 \001(\003\"\232\002\n\022" +
      "PullMessageRequest\022+\n\005group\030\001 \001(\0132\034.apac" +
      "he.rocketmq.v1.Resource\0220\n\tpartition\030\002 \001" +
      "(\0132\035.apache.rocketmq.v1.Partition\022\016\n\006off" +
      "set\030\003 \001(\003\022\022\n\nbatch_size\030\004 \001(\005\022-\n\nawait_t" +
      "ime\030\005 \001(\0132\031.google.protobuf.Duration\022?\n\021" +
      "filter_expression\030\006 \001(\0132$.apache.rocketm" +
      "q.v1.FilterExpression\022\021\n\tclient_id\030\007 \001(\t" +
      "\"\265\001\n\023PullMessageResponse\0222\n\006common\030\001 \001(\013" +
      "2\".apache.rocketmq.v1.ResponseCommon\022\022\n\n" +
      "min_offset\030\002 \001(\003\022\023\n\013next_offset\030\003 \001(\003\022\022\n" +
      "\nmax_offset\030\004 \001(\003\022-\n\010messages\030\005 \003(\0132\033.ap" +
      "ache.rocketmq.v1.Message\"\216\001\n\023UpdateOffse" +
      "tRequest\022+\n\005group\030\001 \001(\0132\034.apache.rocketm" +
      "q.v1.Resource\0220\n\tpartition\030\002 \001(\0132\035.apach" +
      "e.rocketmq.v1.Partition\022\030\n\020partition_off" +
      "set\030\003 \001(\003\"J\n\024UpdateOffsetResponse\0222\n\006com" +
      "mon\030\001 \001(\0132\".apache.rocketmq.v1.ResponseC" +
      "ommon\"\321\001\n\025GenericPollingRequest\022\021\n\tclien" +
      "t_id\030\001 \001(\t\022,\n\006topics\030\002 \003(\0132\034.apache.rock" +
      "etmq.v1.Resource\0226\n\016producer_group\030\003 \001(\013" +
      "2\034.apache.rocketmq.v1.ResourceH\000\0226\n\016cons" +
      "umer_group\030\004 \001(\0132\034.apache.rocketmq.v1.Re" +
      "sourceH\000B\007\n\005group\"L\n\026GenericPollingRespo" +
      "nse\0222\n\006common\030\001 \001(\0132\".apache.rocketmq.v1" +
      ".ResponseCommon\"&\n\027PrintThreadStackReque" +
      "st\022\013\n\003mid\030\001 \001(\t\"p\n\030PrintThreadStackRespo" +
      "nse\0222\n\006common\030\001 \001(\0132\".apache.rocketmq.v1" +
      ".ResponseCommon\022\013\n\003mid\030\002 \001(\t\022\023\n\013stack_tr" +
      "ace\030\003 \001(\t\"\\\n\037VerifyMessageConsumptionReq" +
      "uest\022\013\n\003mid\030\001 \001(\t\022,\n\007message\030\002 \001(\0132\033.apa" +
      "che.rocketmq.v1.Message\"c\n VerifyMessage" +
      "ConsumptionResponse\022\013\n\003mid\030\001 \001(\t\0222\n\006comm" +
      "on\030\002 \001(\0132\".apache.rocketmq.v1.ResponseCo" +
      "mmon\"\200\001\n!RecoverOrphanedTransactionReque" +
      "st\022C\n\036orphaned_transactional_message\030\001 \001" +
      "(\0132\033.apache.rocketmq.v1.Message\022\026\n\016trans" +
      "action_id\030\002 \001(\t\"\235\002\n\023MultiplexingRequest\022" +
      "D\n\017polling_request\030\001 \001(\0132).apache.rocket" +
      "mq.v1.GenericPollingRequestH\000\022S\n\033print_t" +
      "hread_stack_response\030\002 \001(\0132,.apache.rock" +
      "etmq.v1.PrintThreadStackResponseH\000\022c\n#ve" +
      "rify_message_consumption_response\030\003 \001(\0132" +
      "4.apache.rocketmq.v1.VerifyMessageConsum" +
      "ptionResponseH\000B\006\n\004type\"\203\003\n\024Multiplexing" +
      "Response\022F\n\020polling_response\030\001 \001(\0132*.apa" +
      "che.rocketmq.v1.GenericPollingResponseH\000" +
      "\022Q\n\032print_thread_stack_request\030\002 \001(\0132+.a" +
      "pache.rocketmq.v1.PrintThreadStackReques" +
      "tH\000\022a\n\"verify_message_consumption_reques" +
      "t\030\003 \001(\01323.apache.rocketmq.v1.VerifyMessa" +
      "geConsumptionRequestH\000\022e\n$recover_orphan" +
      "ed_transaction_request\030\004 \001(\01325.apache.ro" +
      "cketmq.v1.RecoverOrphanedTransactionRequ" +
      "estH\000B\006\n\004type\"`\n\036NotifyClientTermination" +
      "Request\022+\n\005group\030\001 \001(\0132\034.apache.rocketmq" +
      ".v1.Resource\022\021\n\tclient_id\030\002 \001(\t\"U\n\037Notif" +
      "yClientTerminationResponse\0222\n\006common\030\001 \001" +
      "(\0132\".apache.rocketmq.v1.ResponseCommon2\316" +
      "\014\n\020MessagingService\022]\n\nQueryRoute\022%.apac" +
      "he.rocketmq.v1.QueryRouteRequest\032&.apach" +
      "e.rocketmq.v1.QueryRouteResponse\"\000\022Z\n\tHe" +
      "artbeat\022$.apache.rocketmq.v1.HeartbeatRe" +
      "quest\032%.apache.rocketmq.v1.HeartbeatResp" +
      "onse\"\000\022`\n\013HealthCheck\022&.apache.rocketmq." +
      "v1.HealthCheckRequest\032\'.apache.rocketmq." +
      "v1.HealthCheckResponse\"\000\022`\n\013SendMessage\022" +
      "&.apache.rocketmq.v1.SendMessageRequest\032" +
      "\'.apache.rocketmq.v1.SendMessageResponse" +
      "\"\000\022l\n\017QueryAssignment\022*.apache.rocketmq." +
      "v1.QueryAssignmentRequest\032+.apache.rocke" +
      "tmq.v1.QueryAssignmentResponse\"\000\022i\n\016Rece" +
      "iveMessage\022).apache.rocketmq.v1.ReceiveM" +
      "essageRequest\032*.apache.rocketmq.v1.Recei" +
      "veMessageResponse\"\000\022]\n\nAckMessage\022%.apac" +
      "he.rocketmq.v1.AckMessageRequest\032&.apach" +
      "e.rocketmq.v1.AckMessageResponse\"\000\022`\n\013Na" +
      "ckMessage\022&.apache.rocketmq.v1.NackMessa" +
      "geRequest\032\'.apache.rocketmq.v1.NackMessa" +
      "geResponse\"\000\022\234\001\n\037ForwardMessageToDeadLet" +
      "terQueue\022:.apache.rocketmq.v1.ForwardMes" +
      "sageToDeadLetterQueueRequest\032;.apache.ro" +
      "cketmq.v1.ForwardMessageToDeadLetterQueu" +
      "eResponse\"\000\022i\n\016EndTransaction\022).apache.r" +
      "ocketmq.v1.EndTransactionRequest\032*.apach" +
      "e.rocketmq.v1.EndTransactionResponse\"\000\022`" +
      "\n\013QueryOffset\022&.apache.rocketmq.v1.Query" +
      "OffsetRequest\032\'.apache.rocketmq.v1.Query" +
      "OffsetResponse\"\000\022`\n\013PullMessage\022&.apache" +
      ".rocketmq.v1.PullMessageRequest\032\'.apache" +
      ".rocketmq.v1.PullMessageResponse\"\000\022c\n\014Up" +
      "dateOffset\022\'.apache.rocketmq.v1.UpdateOf" +
      "fsetRequest\032(.apache.rocketmq.v1.UpdateO" +
      "ffsetResponse\"\000\022g\n\020MultiplexingCall\022\'.ap" +
      "ache.rocketmq.v1.MultiplexingRequest\032(.a" +
      "pache.rocketmq.v1.MultiplexingResponse\"\000" +
      "\022\204\001\n\027NotifyClientTermination\0222.apache.ro" +
      "cketmq.v1.NotifyClientTerminationRequest" +
      "\0323.apache.rocketmq.v1.NotifyClientTermin" +
      "ationResponse\"\000B\'\n\022apache.rocketmq.v1B\tM" +
      "QServiceP\001\240\001\001\330\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.rpc.ErrorDetailsProto.getDescriptor(),
          com.google.rpc.CodeProto.getDescriptor(),
          com.google.rpc.StatusProto.getDescriptor(),
          apache.rocketmq.v1.MQDomain.getDescriptor(),
        });
    internal_static_apache_rocketmq_v1_ResponseCommon_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_apache_rocketmq_v1_ResponseCommon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_ResponseCommon_descriptor,
        new java.lang.String[] { "Status", "RequestInfo", "Help", "RetryInfo", "DebugInfo", "ErrorInfo", });
    internal_static_apache_rocketmq_v1_QueryRouteRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_apache_rocketmq_v1_QueryRouteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_QueryRouteRequest_descriptor,
        new java.lang.String[] { "Topic", "Endpoints", });
    internal_static_apache_rocketmq_v1_QueryRouteResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_apache_rocketmq_v1_QueryRouteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_QueryRouteResponse_descriptor,
        new java.lang.String[] { "Common", "Partitions", });
    internal_static_apache_rocketmq_v1_SendMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_apache_rocketmq_v1_SendMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_SendMessageRequest_descriptor,
        new java.lang.String[] { "Message", "Partition", });
    internal_static_apache_rocketmq_v1_SendMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_apache_rocketmq_v1_SendMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_SendMessageResponse_descriptor,
        new java.lang.String[] { "Common", "MessageId", "TransactionId", });
    internal_static_apache_rocketmq_v1_QueryAssignmentRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_apache_rocketmq_v1_QueryAssignmentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_QueryAssignmentRequest_descriptor,
        new java.lang.String[] { "Topic", "Group", "ClientId", "Endpoints", });
    internal_static_apache_rocketmq_v1_QueryAssignmentResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_apache_rocketmq_v1_QueryAssignmentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_QueryAssignmentResponse_descriptor,
        new java.lang.String[] { "Common", "Assignments", });
    internal_static_apache_rocketmq_v1_ReceiveMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_apache_rocketmq_v1_ReceiveMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_ReceiveMessageRequest_descriptor,
        new java.lang.String[] { "Group", "ClientId", "Partition", "FilterExpression", "ConsumePolicy", "InitializationTimestamp", "BatchSize", "InvisibleDuration", "AwaitTime", "FifoFlag", });
    internal_static_apache_rocketmq_v1_ReceiveMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_apache_rocketmq_v1_ReceiveMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_ReceiveMessageResponse_descriptor,
        new java.lang.String[] { "Common", "Messages", "DeliveryTimestamp", "InvisibleDuration", });
    internal_static_apache_rocketmq_v1_AckMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_apache_rocketmq_v1_AckMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_AckMessageRequest_descriptor,
        new java.lang.String[] { "Group", "Topic", "ClientId", "ReceiptHandle", "Offset", "MessageId", "Handle", });
    internal_static_apache_rocketmq_v1_AckMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_apache_rocketmq_v1_AckMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_AckMessageResponse_descriptor,
        new java.lang.String[] { "Common", });
    internal_static_apache_rocketmq_v1_NackMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_apache_rocketmq_v1_NackMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_NackMessageRequest_descriptor,
        new java.lang.String[] { "Group", "Topic", "ClientId", "ReceiptHandle", "MessageId", "DeliveryAttempt", "MaxDeliveryAttempts", });
    internal_static_apache_rocketmq_v1_NackMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_apache_rocketmq_v1_NackMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_NackMessageResponse_descriptor,
        new java.lang.String[] { "Common", });
    internal_static_apache_rocketmq_v1_ForwardMessageToDeadLetterQueueRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_apache_rocketmq_v1_ForwardMessageToDeadLetterQueueRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_ForwardMessageToDeadLetterQueueRequest_descriptor,
        new java.lang.String[] { "Group", "Topic", "ClientId", "ReceiptHandle", "MessageId", "DeliveryAttempt", "MaxDeliveryAttempts", });
    internal_static_apache_rocketmq_v1_ForwardMessageToDeadLetterQueueResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_apache_rocketmq_v1_ForwardMessageToDeadLetterQueueResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_ForwardMessageToDeadLetterQueueResponse_descriptor,
        new java.lang.String[] { "Common", });
    internal_static_apache_rocketmq_v1_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_apache_rocketmq_v1_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_HeartbeatRequest_descriptor,
        new java.lang.String[] { "ClientId", "ProducerData", "ConsumerData", "FifoFlag", "ClientData", });
    internal_static_apache_rocketmq_v1_HeartbeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_apache_rocketmq_v1_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_HeartbeatResponse_descriptor,
        new java.lang.String[] { "Common", });
    internal_static_apache_rocketmq_v1_HealthCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_apache_rocketmq_v1_HealthCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_HealthCheckRequest_descriptor,
        new java.lang.String[] { "Group", "ClientHost", });
    internal_static_apache_rocketmq_v1_HealthCheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_apache_rocketmq_v1_HealthCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_HealthCheckResponse_descriptor,
        new java.lang.String[] { "Common", });
    internal_static_apache_rocketmq_v1_EndTransactionRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_apache_rocketmq_v1_EndTransactionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_EndTransactionRequest_descriptor,
        new java.lang.String[] { "Group", "MessageId", "TransactionId", "Resolution", "Source", "TraceContext", });
    internal_static_apache_rocketmq_v1_EndTransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_apache_rocketmq_v1_EndTransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_EndTransactionResponse_descriptor,
        new java.lang.String[] { "Common", });
    internal_static_apache_rocketmq_v1_QueryOffsetRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_apache_rocketmq_v1_QueryOffsetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_QueryOffsetRequest_descriptor,
        new java.lang.String[] { "Partition", "Policy", "TimePoint", });
    internal_static_apache_rocketmq_v1_QueryOffsetResponse_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_apache_rocketmq_v1_QueryOffsetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_QueryOffsetResponse_descriptor,
        new java.lang.String[] { "Common", "Offset", });
    internal_static_apache_rocketmq_v1_PullMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_apache_rocketmq_v1_PullMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_PullMessageRequest_descriptor,
        new java.lang.String[] { "Group", "Partition", "Offset", "BatchSize", "AwaitTime", "FilterExpression", "ClientId", });
    internal_static_apache_rocketmq_v1_PullMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_apache_rocketmq_v1_PullMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_PullMessageResponse_descriptor,
        new java.lang.String[] { "Common", "MinOffset", "NextOffset", "MaxOffset", "Messages", });
    internal_static_apache_rocketmq_v1_UpdateOffsetRequest_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_apache_rocketmq_v1_UpdateOffsetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_UpdateOffsetRequest_descriptor,
        new java.lang.String[] { "Group", "Partition", "PartitionOffset", });
    internal_static_apache_rocketmq_v1_UpdateOffsetResponse_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_apache_rocketmq_v1_UpdateOffsetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_UpdateOffsetResponse_descriptor,
        new java.lang.String[] { "Common", });
    internal_static_apache_rocketmq_v1_GenericPollingRequest_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_apache_rocketmq_v1_GenericPollingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_GenericPollingRequest_descriptor,
        new java.lang.String[] { "ClientId", "Topics", "ProducerGroup", "ConsumerGroup", "Group", });
    internal_static_apache_rocketmq_v1_GenericPollingResponse_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_apache_rocketmq_v1_GenericPollingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_GenericPollingResponse_descriptor,
        new java.lang.String[] { "Common", });
    internal_static_apache_rocketmq_v1_PrintThreadStackRequest_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_apache_rocketmq_v1_PrintThreadStackRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_PrintThreadStackRequest_descriptor,
        new java.lang.String[] { "Mid", });
    internal_static_apache_rocketmq_v1_PrintThreadStackResponse_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_apache_rocketmq_v1_PrintThreadStackResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_PrintThreadStackResponse_descriptor,
        new java.lang.String[] { "Common", "Mid", "StackTrace", });
    internal_static_apache_rocketmq_v1_VerifyMessageConsumptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_apache_rocketmq_v1_VerifyMessageConsumptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_VerifyMessageConsumptionRequest_descriptor,
        new java.lang.String[] { "Mid", "Message", });
    internal_static_apache_rocketmq_v1_VerifyMessageConsumptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_apache_rocketmq_v1_VerifyMessageConsumptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_VerifyMessageConsumptionResponse_descriptor,
        new java.lang.String[] { "Mid", "Common", });
    internal_static_apache_rocketmq_v1_RecoverOrphanedTransactionRequest_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_apache_rocketmq_v1_RecoverOrphanedTransactionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_RecoverOrphanedTransactionRequest_descriptor,
        new java.lang.String[] { "OrphanedTransactionalMessage", "TransactionId", });
    internal_static_apache_rocketmq_v1_MultiplexingRequest_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_apache_rocketmq_v1_MultiplexingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_MultiplexingRequest_descriptor,
        new java.lang.String[] { "PollingRequest", "PrintThreadStackResponse", "VerifyMessageConsumptionResponse", "Type", });
    internal_static_apache_rocketmq_v1_MultiplexingResponse_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_apache_rocketmq_v1_MultiplexingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_MultiplexingResponse_descriptor,
        new java.lang.String[] { "PollingResponse", "PrintThreadStackRequest", "VerifyMessageConsumptionRequest", "RecoverOrphanedTransactionRequest", "Type", });
    internal_static_apache_rocketmq_v1_NotifyClientTerminationRequest_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_apache_rocketmq_v1_NotifyClientTerminationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_NotifyClientTerminationRequest_descriptor,
        new java.lang.String[] { "Group", "ClientId", });
    internal_static_apache_rocketmq_v1_NotifyClientTerminationResponse_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_apache_rocketmq_v1_NotifyClientTerminationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apache_rocketmq_v1_NotifyClientTerminationResponse_descriptor,
        new java.lang.String[] { "Common", });
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.rpc.ErrorDetailsProto.getDescriptor();
    com.google.rpc.CodeProto.getDescriptor();
    com.google.rpc.StatusProto.getDescriptor();
    apache.rocketmq.v1.MQDomain.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
