// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v1/service.proto

package apache.rocketmq.v1;

public interface MultiplexingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apache.rocketmq.v1.MultiplexingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.apache.rocketmq.v1.GenericPollingRequest polling_request = 1;</code>
   * @return Whether the pollingRequest field is set.
   */
  boolean hasPollingRequest();
  /**
   * <code>.apache.rocketmq.v1.GenericPollingRequest polling_request = 1;</code>
   * @return The pollingRequest.
   */
  apache.rocketmq.v1.GenericPollingRequest getPollingRequest();
  /**
   * <code>.apache.rocketmq.v1.GenericPollingRequest polling_request = 1;</code>
   */
  apache.rocketmq.v1.GenericPollingRequestOrBuilder getPollingRequestOrBuilder();

  /**
   * <code>.apache.rocketmq.v1.PrintThreadStackResponse print_thread_stack_response = 2;</code>
   * @return Whether the printThreadStackResponse field is set.
   */
  boolean hasPrintThreadStackResponse();
  /**
   * <code>.apache.rocketmq.v1.PrintThreadStackResponse print_thread_stack_response = 2;</code>
   * @return The printThreadStackResponse.
   */
  apache.rocketmq.v1.PrintThreadStackResponse getPrintThreadStackResponse();
  /**
   * <code>.apache.rocketmq.v1.PrintThreadStackResponse print_thread_stack_response = 2;</code>
   */
  apache.rocketmq.v1.PrintThreadStackResponseOrBuilder getPrintThreadStackResponseOrBuilder();

  /**
   * <code>.apache.rocketmq.v1.VerifyMessageConsumptionResponse verify_message_consumption_response = 3;</code>
   * @return Whether the verifyMessageConsumptionResponse field is set.
   */
  boolean hasVerifyMessageConsumptionResponse();
  /**
   * <code>.apache.rocketmq.v1.VerifyMessageConsumptionResponse verify_message_consumption_response = 3;</code>
   * @return The verifyMessageConsumptionResponse.
   */
  apache.rocketmq.v1.VerifyMessageConsumptionResponse getVerifyMessageConsumptionResponse();
  /**
   * <code>.apache.rocketmq.v1.VerifyMessageConsumptionResponse verify_message_consumption_response = 3;</code>
   */
  apache.rocketmq.v1.VerifyMessageConsumptionResponseOrBuilder getVerifyMessageConsumptionResponseOrBuilder();

  public apache.rocketmq.v1.MultiplexingRequest.TypeCase getTypeCase();
}
