// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apache/rocketmq/v1/service.proto

package apache.rocketmq.v1;

public interface SeekCursorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apache.rocketmq.v1.SeekCursorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.apache.rocketmq.v1.ResponseCommon common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.apache.rocketmq.v1.ResponseCommon common = 1;</code>
   * @return The common.
   */
  apache.rocketmq.v1.ResponseCommon getCommon();
  /**
   * <code>.apache.rocketmq.v1.ResponseCommon common = 1;</code>
   */
  apache.rocketmq.v1.ResponseCommonOrBuilder getCommonOrBuilder();

  /**
   * <code>.apache.rocketmq.v1.Offset offset = 2;</code>
   * @return Whether the offset field is set.
   */
  boolean hasOffset();
  /**
   * <code>.apache.rocketmq.v1.Offset offset = 2;</code>
   * @return The offset.
   */
  apache.rocketmq.v1.Offset getOffset();
  /**
   * <code>.apache.rocketmq.v1.Offset offset = 2;</code>
   */
  apache.rocketmq.v1.OffsetOrBuilder getOffsetOrBuilder();
}
