// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rocketmq.proto

package org.apache.rocketmq.proto;

/**
 * Protobuf type {@code rocketmq.rpc.api.BrokerData}
 */
public  final class BrokerData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rocketmq.rpc.api.BrokerData)
    BrokerDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BrokerData.newBuilder() to construct.
  private BrokerData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BrokerData() {
    cluster_ = "";
    brokerName_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BrokerData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            cluster_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            brokerName_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              addresses_ = com.google.protobuf.MapField.newMapField(
                  AddressesDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000004;
            }
            com.google.protobuf.MapEntry<java.lang.Long, java.lang.String>
            addresses__ = input.readMessage(
                AddressesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            addresses_.getMutableMap().put(
                addresses__.getKey(), addresses__.getValue());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.apache.rocketmq.proto.ACS.internal_static_rocketmq_rpc_api_BrokerData_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 3:
        return internalGetAddresses();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.apache.rocketmq.proto.ACS.internal_static_rocketmq_rpc_api_BrokerData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.apache.rocketmq.proto.BrokerData.class, org.apache.rocketmq.proto.BrokerData.Builder.class);
  }

  private int bitField0_;
  public static final int CLUSTER_FIELD_NUMBER = 1;
  private volatile java.lang.Object cluster_;
  /**
   * <code>string cluster = 1;</code>
   */
  public java.lang.String getCluster() {
    java.lang.Object ref = cluster_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cluster_ = s;
      return s;
    }
  }
  /**
   * <code>string cluster = 1;</code>
   */
  public com.google.protobuf.ByteString
      getClusterBytes() {
    java.lang.Object ref = cluster_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cluster_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BROKER_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object brokerName_;
  /**
   * <code>string broker_name = 2;</code>
   */
  public java.lang.String getBrokerName() {
    java.lang.Object ref = brokerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      brokerName_ = s;
      return s;
    }
  }
  /**
   * <code>string broker_name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getBrokerNameBytes() {
    java.lang.Object ref = brokerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      brokerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRESSES_FIELD_NUMBER = 3;
  private static final class AddressesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Long, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Long, java.lang.String>newDefaultInstance(
                org.apache.rocketmq.proto.ACS.internal_static_rocketmq_rpc_api_BrokerData_AddressesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT64,
                0L,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.Long, java.lang.String> addresses_;
  private com.google.protobuf.MapField<java.lang.Long, java.lang.String>
  internalGetAddresses() {
    if (addresses_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          AddressesDefaultEntryHolder.defaultEntry);
    }
    return addresses_;
  }

  public int getAddressesCount() {
    return internalGetAddresses().getMap().size();
  }
  /**
   * <code>map&lt;int64, string&gt; addresses = 3;</code>
   */

  public boolean containsAddresses(
      long key) {
    
    return internalGetAddresses().getMap().containsKey(key);
  }
  /**
   * Use {@link #getAddressesMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.Long, java.lang.String> getAddresses() {
    return getAddressesMap();
  }
  /**
   * <code>map&lt;int64, string&gt; addresses = 3;</code>
   */

  public java.util.Map<java.lang.Long, java.lang.String> getAddressesMap() {
    return internalGetAddresses().getMap();
  }
  /**
   * <code>map&lt;int64, string&gt; addresses = 3;</code>
   */

  public java.lang.String getAddressesOrDefault(
      long key,
      java.lang.String defaultValue) {
    
    java.util.Map<java.lang.Long, java.lang.String> map =
        internalGetAddresses().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int64, string&gt; addresses = 3;</code>
   */

  public java.lang.String getAddressesOrThrow(
      long key) {
    
    java.util.Map<java.lang.Long, java.lang.String> map =
        internalGetAddresses().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getClusterBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cluster_);
    }
    if (!getBrokerNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, brokerName_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeLongMapTo(
        output,
        internalGetAddresses(),
        AddressesDefaultEntryHolder.defaultEntry,
        3);
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getClusterBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cluster_);
    }
    if (!getBrokerNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, brokerName_);
    }
    for (java.util.Map.Entry<java.lang.Long, java.lang.String> entry
         : internalGetAddresses().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Long, java.lang.String>
      addresses__ = AddressesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, addresses__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.apache.rocketmq.proto.BrokerData)) {
      return super.equals(obj);
    }
    org.apache.rocketmq.proto.BrokerData other = (org.apache.rocketmq.proto.BrokerData) obj;

    boolean result = true;
    result = result && getCluster()
        .equals(other.getCluster());
    result = result && getBrokerName()
        .equals(other.getBrokerName());
    result = result && internalGetAddresses().equals(
        other.internalGetAddresses());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLUSTER_FIELD_NUMBER;
    hash = (53 * hash) + getCluster().hashCode();
    hash = (37 * hash) + BROKER_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getBrokerName().hashCode();
    if (!internalGetAddresses().getMap().isEmpty()) {
      hash = (37 * hash) + ADDRESSES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetAddresses().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.apache.rocketmq.proto.BrokerData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.rocketmq.proto.BrokerData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.rocketmq.proto.BrokerData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.rocketmq.proto.BrokerData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.rocketmq.proto.BrokerData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.rocketmq.proto.BrokerData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.rocketmq.proto.BrokerData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.rocketmq.proto.BrokerData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.rocketmq.proto.BrokerData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.apache.rocketmq.proto.BrokerData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.rocketmq.proto.BrokerData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.rocketmq.proto.BrokerData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.apache.rocketmq.proto.BrokerData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rocketmq.rpc.api.BrokerData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rocketmq.rpc.api.BrokerData)
      org.apache.rocketmq.proto.BrokerDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.rocketmq.proto.ACS.internal_static_rocketmq_rpc_api_BrokerData_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetAddresses();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableAddresses();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.rocketmq.proto.ACS.internal_static_rocketmq_rpc_api_BrokerData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.rocketmq.proto.BrokerData.class, org.apache.rocketmq.proto.BrokerData.Builder.class);
    }

    // Construct using org.apache.rocketmq.proto.BrokerData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      cluster_ = "";

      brokerName_ = "";

      internalGetMutableAddresses().clear();
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.apache.rocketmq.proto.ACS.internal_static_rocketmq_rpc_api_BrokerData_descriptor;
    }

    public org.apache.rocketmq.proto.BrokerData getDefaultInstanceForType() {
      return org.apache.rocketmq.proto.BrokerData.getDefaultInstance();
    }

    public org.apache.rocketmq.proto.BrokerData build() {
      org.apache.rocketmq.proto.BrokerData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.apache.rocketmq.proto.BrokerData buildPartial() {
      org.apache.rocketmq.proto.BrokerData result = new org.apache.rocketmq.proto.BrokerData(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.cluster_ = cluster_;
      result.brokerName_ = brokerName_;
      result.addresses_ = internalGetAddresses();
      result.addresses_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.apache.rocketmq.proto.BrokerData) {
        return mergeFrom((org.apache.rocketmq.proto.BrokerData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.apache.rocketmq.proto.BrokerData other) {
      if (other == org.apache.rocketmq.proto.BrokerData.getDefaultInstance()) return this;
      if (!other.getCluster().isEmpty()) {
        cluster_ = other.cluster_;
        onChanged();
      }
      if (!other.getBrokerName().isEmpty()) {
        brokerName_ = other.brokerName_;
        onChanged();
      }
      internalGetMutableAddresses().mergeFrom(
          other.internalGetAddresses());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.apache.rocketmq.proto.BrokerData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.apache.rocketmq.proto.BrokerData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object cluster_ = "";
    /**
     * <code>string cluster = 1;</code>
     */
    public java.lang.String getCluster() {
      java.lang.Object ref = cluster_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cluster_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cluster = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClusterBytes() {
      java.lang.Object ref = cluster_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cluster_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cluster = 1;</code>
     */
    public Builder setCluster(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cluster_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cluster = 1;</code>
     */
    public Builder clearCluster() {
      
      cluster_ = getDefaultInstance().getCluster();
      onChanged();
      return this;
    }
    /**
     * <code>string cluster = 1;</code>
     */
    public Builder setClusterBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cluster_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object brokerName_ = "";
    /**
     * <code>string broker_name = 2;</code>
     */
    public java.lang.String getBrokerName() {
      java.lang.Object ref = brokerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        brokerName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string broker_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBrokerNameBytes() {
      java.lang.Object ref = brokerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brokerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string broker_name = 2;</code>
     */
    public Builder setBrokerName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      brokerName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string broker_name = 2;</code>
     */
    public Builder clearBrokerName() {
      
      brokerName_ = getDefaultInstance().getBrokerName();
      onChanged();
      return this;
    }
    /**
     * <code>string broker_name = 2;</code>
     */
    public Builder setBrokerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      brokerName_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.Long, java.lang.String> addresses_;
    private com.google.protobuf.MapField<java.lang.Long, java.lang.String>
    internalGetAddresses() {
      if (addresses_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AddressesDefaultEntryHolder.defaultEntry);
      }
      return addresses_;
    }
    private com.google.protobuf.MapField<java.lang.Long, java.lang.String>
    internalGetMutableAddresses() {
      onChanged();;
      if (addresses_ == null) {
        addresses_ = com.google.protobuf.MapField.newMapField(
            AddressesDefaultEntryHolder.defaultEntry);
      }
      if (!addresses_.isMutable()) {
        addresses_ = addresses_.copy();
      }
      return addresses_;
    }

    public int getAddressesCount() {
      return internalGetAddresses().getMap().size();
    }
    /**
     * <code>map&lt;int64, string&gt; addresses = 3;</code>
     */

    public boolean containsAddresses(
        long key) {
      
      return internalGetAddresses().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAddressesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, java.lang.String> getAddresses() {
      return getAddressesMap();
    }
    /**
     * <code>map&lt;int64, string&gt; addresses = 3;</code>
     */

    public java.util.Map<java.lang.Long, java.lang.String> getAddressesMap() {
      return internalGetAddresses().getMap();
    }
    /**
     * <code>map&lt;int64, string&gt; addresses = 3;</code>
     */

    public java.lang.String getAddressesOrDefault(
        long key,
        java.lang.String defaultValue) {
      
      java.util.Map<java.lang.Long, java.lang.String> map =
          internalGetAddresses().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int64, string&gt; addresses = 3;</code>
     */

    public java.lang.String getAddressesOrThrow(
        long key) {
      
      java.util.Map<java.lang.Long, java.lang.String> map =
          internalGetAddresses().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearAddresses() {
      internalGetMutableAddresses().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;int64, string&gt; addresses = 3;</code>
     */

    public Builder removeAddresses(
        long key) {
      
      internalGetMutableAddresses().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, java.lang.String>
    getMutableAddresses() {
      return internalGetMutableAddresses().getMutableMap();
    }
    /**
     * <code>map&lt;int64, string&gt; addresses = 3;</code>
     */
    public Builder putAddresses(
        long key,
        java.lang.String value) {
      
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableAddresses().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;int64, string&gt; addresses = 3;</code>
     */

    public Builder putAllAddresses(
        java.util.Map<java.lang.Long, java.lang.String> values) {
      internalGetMutableAddresses().getMutableMap()
          .putAll(values);
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rocketmq.rpc.api.BrokerData)
  }

  // @@protoc_insertion_point(class_scope:rocketmq.rpc.api.BrokerData)
  private static final org.apache.rocketmq.proto.BrokerData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.apache.rocketmq.proto.BrokerData();
  }

  public static org.apache.rocketmq.proto.BrokerData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BrokerData>
      PARSER = new com.google.protobuf.AbstractParser<BrokerData>() {
    public BrokerData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BrokerData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BrokerData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BrokerData> getParserForType() {
    return PARSER;
  }

  public org.apache.rocketmq.proto.BrokerData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

