// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rocketmq.proto

package org.apache.rocketmq.proto;

public interface EndTransactionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rocketmq.rpc.api.EndTransactionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string producer_group = 1;</code>
   */
  java.lang.String getProducerGroup();
  /**
   * <code>string producer_group = 1;</code>
   */
  com.google.protobuf.ByteString
      getProducerGroupBytes();

  /**
   * <code>int64 transaction_state_table_offset = 2;</code>
   */
  long getTransactionStateTableOffset();

  /**
   * <code>int64 commit_log_offset = 3;</code>
   */
  long getCommitLogOffset();

  /**
   * <code>.rocketmq.rpc.api.EndTransactionRequest.Resolution resolution = 4;</code>
   */
  int getResolutionValue();
  /**
   * <code>.rocketmq.rpc.api.EndTransactionRequest.Resolution resolution = 4;</code>
   */
  org.apache.rocketmq.proto.EndTransactionRequest.Resolution getResolution();

  /**
   * <code>bool from_transaction_check = 5;</code>
   */
  boolean getFromTransactionCheck();

  /**
   * <code>string msg_id = 6;</code>
   */
  java.lang.String getMsgId();
  /**
   * <code>string msg_id = 6;</code>
   */
  com.google.protobuf.ByteString
      getMsgIdBytes();

  /**
   * <code>string transaction_id = 7;</code>
   */
  java.lang.String getTransactionId();
  /**
   * <code>string transaction_id = 7;</code>
   */
  com.google.protobuf.ByteString
      getTransactionIdBytes();

  /**
   * <code>string broker_name = 8;</code>
   */
  java.lang.String getBrokerName();
  /**
   * <code>string broker_name = 8;</code>
   */
  com.google.protobuf.ByteString
      getBrokerNameBytes();
}
