// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rocketmq.proto

package org.apache.rocketmq.proto;

public interface MessageExtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rocketmq.rpc.api.MessageExt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rocketmq.rpc.api.Message base = 1;</code>
   * @return Whether the base field is set.
   */
  boolean hasBase();
  /**
   * <code>.rocketmq.rpc.api.Message base = 1;</code>
   * @return The base.
   */
  org.apache.rocketmq.proto.Message getBase();
  /**
   * <code>.rocketmq.rpc.api.Message base = 1;</code>
   */
  org.apache.rocketmq.proto.MessageOrBuilder getBaseOrBuilder();

  /**
   * <code>.rocketmq.rpc.api.MessageExt.Extension extension = 2;</code>
   * @return Whether the extension field is set.
   */
  boolean hasExtension();
  /**
   * <code>.rocketmq.rpc.api.MessageExt.Extension extension = 2;</code>
   * @return The extension.
   */
  org.apache.rocketmq.proto.MessageExt.Extension getExtension();
  /**
   * <code>.rocketmq.rpc.api.MessageExt.Extension extension = 2;</code>
   */
  org.apache.rocketmq.proto.MessageExt.ExtensionOrBuilder getExtensionOrBuilder();
}
