// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rocketmq.proto

package org.apache.rocketmq.proto;

public interface MessageQueueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rocketmq.rpc.api.MessageQueue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string topic = 1;</code>
   * @return The topic.
   */
  java.lang.String getTopic();
  /**
   * <code>string topic = 1;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <code>string broker_name = 2;</code>
   * @return The brokerName.
   */
  java.lang.String getBrokerName();
  /**
   * <code>string broker_name = 2;</code>
   * @return The bytes for brokerName.
   */
  com.google.protobuf.ByteString
      getBrokerNameBytes();

  /**
   * <code>int32 queue_id = 3;</code>
   * @return The queueId.
   */
  int getQueueId();
}
