// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rocketmq.proto

package org.apache.rocketmq.proto;

/**
 * Protobuf type {@code rocketmq.rpc.api.RouteInfoResponse}
 */
public final class RouteInfoResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rocketmq.rpc.api.RouteInfoResponse)
    RouteInfoResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RouteInfoResponse.newBuilder() to construct.
  private RouteInfoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RouteInfoResponse() {
    code_ = 0;
    remark_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RouteInfoResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RouteInfoResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            code_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            remark_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              route_ = com.google.protobuf.MapField.newMapField(
                  RouteDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, org.apache.rocketmq.proto.TopicRouteData>
            route__ = input.readMessage(
                RouteDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            route_.getMutableMap().put(
                route__.getKey(), route__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.apache.rocketmq.proto.ACS.internal_static_rocketmq_rpc_api_RouteInfoResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 3:
        return internalGetRoute();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.apache.rocketmq.proto.ACS.internal_static_rocketmq_rpc_api_RouteInfoResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.apache.rocketmq.proto.RouteInfoResponse.class, org.apache.rocketmq.proto.RouteInfoResponse.Builder.class);
  }

  public static final int CODE_FIELD_NUMBER = 1;
  private int code_;
  /**
   * <code>.rocketmq.rpc.api.ResponseCode code = 1;</code>
   * @return The enum numeric value on the wire for code.
   */
  @java.lang.Override public int getCodeValue() {
    return code_;
  }
  /**
   * <code>.rocketmq.rpc.api.ResponseCode code = 1;</code>
   * @return The code.
   */
  @java.lang.Override public org.apache.rocketmq.proto.ResponseCode getCode() {
    @SuppressWarnings("deprecation")
    org.apache.rocketmq.proto.ResponseCode result = org.apache.rocketmq.proto.ResponseCode.valueOf(code_);
    return result == null ? org.apache.rocketmq.proto.ResponseCode.UNRECOGNIZED : result;
  }

  public static final int REMARK_FIELD_NUMBER = 2;
  private volatile java.lang.Object remark_;
  /**
   * <code>string remark = 2;</code>
   * @return The remark.
   */
  @java.lang.Override
  public java.lang.String getRemark() {
    java.lang.Object ref = remark_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      remark_ = s;
      return s;
    }
  }
  /**
   * <code>string remark = 2;</code>
   * @return The bytes for remark.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRemarkBytes() {
    java.lang.Object ref = remark_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      remark_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROUTE_FIELD_NUMBER = 3;
  private static final class RouteDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, org.apache.rocketmq.proto.TopicRouteData> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, org.apache.rocketmq.proto.TopicRouteData>newDefaultInstance(
                org.apache.rocketmq.proto.ACS.internal_static_rocketmq_rpc_api_RouteInfoResponse_RouteEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                org.apache.rocketmq.proto.TopicRouteData.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, org.apache.rocketmq.proto.TopicRouteData> route_;
  private com.google.protobuf.MapField<java.lang.String, org.apache.rocketmq.proto.TopicRouteData>
  internalGetRoute() {
    if (route_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          RouteDefaultEntryHolder.defaultEntry);
    }
    return route_;
  }

  public int getRouteCount() {
    return internalGetRoute().getMap().size();
  }
  /**
   * <code>map&lt;string, .rocketmq.rpc.api.TopicRouteData&gt; route = 3;</code>
   */

  @java.lang.Override
  public boolean containsRoute(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetRoute().getMap().containsKey(key);
  }
  /**
   * Use {@link #getRouteMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, org.apache.rocketmq.proto.TopicRouteData> getRoute() {
    return getRouteMap();
  }
  /**
   * <code>map&lt;string, .rocketmq.rpc.api.TopicRouteData&gt; route = 3;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, org.apache.rocketmq.proto.TopicRouteData> getRouteMap() {
    return internalGetRoute().getMap();
  }
  /**
   * <code>map&lt;string, .rocketmq.rpc.api.TopicRouteData&gt; route = 3;</code>
   */
  @java.lang.Override

  public org.apache.rocketmq.proto.TopicRouteData getRouteOrDefault(
      java.lang.String key,
      org.apache.rocketmq.proto.TopicRouteData defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, org.apache.rocketmq.proto.TopicRouteData> map =
        internalGetRoute().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .rocketmq.rpc.api.TopicRouteData&gt; route = 3;</code>
   */
  @java.lang.Override

  public org.apache.rocketmq.proto.TopicRouteData getRouteOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, org.apache.rocketmq.proto.TopicRouteData> map =
        internalGetRoute().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (code_ != org.apache.rocketmq.proto.ResponseCode.SUCCESS.getNumber()) {
      output.writeEnum(1, code_);
    }
    if (!getRemarkBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, remark_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetRoute(),
        RouteDefaultEntryHolder.defaultEntry,
        3);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (code_ != org.apache.rocketmq.proto.ResponseCode.SUCCESS.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, code_);
    }
    if (!getRemarkBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, remark_);
    }
    for (java.util.Map.Entry<java.lang.String, org.apache.rocketmq.proto.TopicRouteData> entry
         : internalGetRoute().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, org.apache.rocketmq.proto.TopicRouteData>
      route__ = RouteDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, route__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.apache.rocketmq.proto.RouteInfoResponse)) {
      return super.equals(obj);
    }
    org.apache.rocketmq.proto.RouteInfoResponse other = (org.apache.rocketmq.proto.RouteInfoResponse) obj;

    if (code_ != other.code_) return false;
    if (!getRemark()
        .equals(other.getRemark())) return false;
    if (!internalGetRoute().equals(
        other.internalGetRoute())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + code_;
    hash = (37 * hash) + REMARK_FIELD_NUMBER;
    hash = (53 * hash) + getRemark().hashCode();
    if (!internalGetRoute().getMap().isEmpty()) {
      hash = (37 * hash) + ROUTE_FIELD_NUMBER;
      hash = (53 * hash) + internalGetRoute().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.apache.rocketmq.proto.RouteInfoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.rocketmq.proto.RouteInfoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.rocketmq.proto.RouteInfoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.rocketmq.proto.RouteInfoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.rocketmq.proto.RouteInfoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.rocketmq.proto.RouteInfoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.rocketmq.proto.RouteInfoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.rocketmq.proto.RouteInfoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.rocketmq.proto.RouteInfoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.apache.rocketmq.proto.RouteInfoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.rocketmq.proto.RouteInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.rocketmq.proto.RouteInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.apache.rocketmq.proto.RouteInfoResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rocketmq.rpc.api.RouteInfoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rocketmq.rpc.api.RouteInfoResponse)
      org.apache.rocketmq.proto.RouteInfoResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.rocketmq.proto.ACS.internal_static_rocketmq_rpc_api_RouteInfoResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetRoute();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableRoute();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.rocketmq.proto.ACS.internal_static_rocketmq_rpc_api_RouteInfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.rocketmq.proto.RouteInfoResponse.class, org.apache.rocketmq.proto.RouteInfoResponse.Builder.class);
    }

    // Construct using org.apache.rocketmq.proto.RouteInfoResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      code_ = 0;

      remark_ = "";

      internalGetMutableRoute().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.apache.rocketmq.proto.ACS.internal_static_rocketmq_rpc_api_RouteInfoResponse_descriptor;
    }

    @java.lang.Override
    public org.apache.rocketmq.proto.RouteInfoResponse getDefaultInstanceForType() {
      return org.apache.rocketmq.proto.RouteInfoResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.apache.rocketmq.proto.RouteInfoResponse build() {
      org.apache.rocketmq.proto.RouteInfoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.apache.rocketmq.proto.RouteInfoResponse buildPartial() {
      org.apache.rocketmq.proto.RouteInfoResponse result = new org.apache.rocketmq.proto.RouteInfoResponse(this);
      int from_bitField0_ = bitField0_;
      result.code_ = code_;
      result.remark_ = remark_;
      result.route_ = internalGetRoute();
      result.route_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.apache.rocketmq.proto.RouteInfoResponse) {
        return mergeFrom((org.apache.rocketmq.proto.RouteInfoResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.apache.rocketmq.proto.RouteInfoResponse other) {
      if (other == org.apache.rocketmq.proto.RouteInfoResponse.getDefaultInstance()) return this;
      if (other.code_ != 0) {
        setCodeValue(other.getCodeValue());
      }
      if (!other.getRemark().isEmpty()) {
        remark_ = other.remark_;
        onChanged();
      }
      internalGetMutableRoute().mergeFrom(
          other.internalGetRoute());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.apache.rocketmq.proto.RouteInfoResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.apache.rocketmq.proto.RouteInfoResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int code_ = 0;
    /**
     * <code>.rocketmq.rpc.api.ResponseCode code = 1;</code>
     * @return The enum numeric value on the wire for code.
     */
    @java.lang.Override public int getCodeValue() {
      return code_;
    }
    /**
     * <code>.rocketmq.rpc.api.ResponseCode code = 1;</code>
     * @param value The enum numeric value on the wire for code to set.
     * @return This builder for chaining.
     */
    public Builder setCodeValue(int value) {
      
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.rocketmq.rpc.api.ResponseCode code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public org.apache.rocketmq.proto.ResponseCode getCode() {
      @SuppressWarnings("deprecation")
      org.apache.rocketmq.proto.ResponseCode result = org.apache.rocketmq.proto.ResponseCode.valueOf(code_);
      return result == null ? org.apache.rocketmq.proto.ResponseCode.UNRECOGNIZED : result;
    }
    /**
     * <code>.rocketmq.rpc.api.ResponseCode code = 1;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(org.apache.rocketmq.proto.ResponseCode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      code_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.rocketmq.rpc.api.ResponseCode code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      
      code_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object remark_ = "";
    /**
     * <code>string remark = 2;</code>
     * @return The remark.
     */
    public java.lang.String getRemark() {
      java.lang.Object ref = remark_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        remark_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string remark = 2;</code>
     * @return The bytes for remark.
     */
    public com.google.protobuf.ByteString
        getRemarkBytes() {
      java.lang.Object ref = remark_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string remark = 2;</code>
     * @param value The remark to set.
     * @return This builder for chaining.
     */
    public Builder setRemark(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      remark_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string remark = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRemark() {
      
      remark_ = getDefaultInstance().getRemark();
      onChanged();
      return this;
    }
    /**
     * <code>string remark = 2;</code>
     * @param value The bytes for remark to set.
     * @return This builder for chaining.
     */
    public Builder setRemarkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      remark_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, org.apache.rocketmq.proto.TopicRouteData> route_;
    private com.google.protobuf.MapField<java.lang.String, org.apache.rocketmq.proto.TopicRouteData>
    internalGetRoute() {
      if (route_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            RouteDefaultEntryHolder.defaultEntry);
      }
      return route_;
    }
    private com.google.protobuf.MapField<java.lang.String, org.apache.rocketmq.proto.TopicRouteData>
    internalGetMutableRoute() {
      onChanged();;
      if (route_ == null) {
        route_ = com.google.protobuf.MapField.newMapField(
            RouteDefaultEntryHolder.defaultEntry);
      }
      if (!route_.isMutable()) {
        route_ = route_.copy();
      }
      return route_;
    }

    public int getRouteCount() {
      return internalGetRoute().getMap().size();
    }
    /**
     * <code>map&lt;string, .rocketmq.rpc.api.TopicRouteData&gt; route = 3;</code>
     */

    @java.lang.Override
    public boolean containsRoute(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetRoute().getMap().containsKey(key);
    }
    /**
     * Use {@link #getRouteMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, org.apache.rocketmq.proto.TopicRouteData> getRoute() {
      return getRouteMap();
    }
    /**
     * <code>map&lt;string, .rocketmq.rpc.api.TopicRouteData&gt; route = 3;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, org.apache.rocketmq.proto.TopicRouteData> getRouteMap() {
      return internalGetRoute().getMap();
    }
    /**
     * <code>map&lt;string, .rocketmq.rpc.api.TopicRouteData&gt; route = 3;</code>
     */
    @java.lang.Override

    public org.apache.rocketmq.proto.TopicRouteData getRouteOrDefault(
        java.lang.String key,
        org.apache.rocketmq.proto.TopicRouteData defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, org.apache.rocketmq.proto.TopicRouteData> map =
          internalGetRoute().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .rocketmq.rpc.api.TopicRouteData&gt; route = 3;</code>
     */
    @java.lang.Override

    public org.apache.rocketmq.proto.TopicRouteData getRouteOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, org.apache.rocketmq.proto.TopicRouteData> map =
          internalGetRoute().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearRoute() {
      internalGetMutableRoute().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .rocketmq.rpc.api.TopicRouteData&gt; route = 3;</code>
     */

    public Builder removeRoute(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableRoute().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, org.apache.rocketmq.proto.TopicRouteData>
    getMutableRoute() {
      return internalGetMutableRoute().getMutableMap();
    }
    /**
     * <code>map&lt;string, .rocketmq.rpc.api.TopicRouteData&gt; route = 3;</code>
     */
    public Builder putRoute(
        java.lang.String key,
        org.apache.rocketmq.proto.TopicRouteData value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableRoute().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .rocketmq.rpc.api.TopicRouteData&gt; route = 3;</code>
     */

    public Builder putAllRoute(
        java.util.Map<java.lang.String, org.apache.rocketmq.proto.TopicRouteData> values) {
      internalGetMutableRoute().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rocketmq.rpc.api.RouteInfoResponse)
  }

  // @@protoc_insertion_point(class_scope:rocketmq.rpc.api.RouteInfoResponse)
  private static final org.apache.rocketmq.proto.RouteInfoResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.apache.rocketmq.proto.RouteInfoResponse();
  }

  public static org.apache.rocketmq.proto.RouteInfoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RouteInfoResponse>
      PARSER = new com.google.protobuf.AbstractParser<RouteInfoResponse>() {
    @java.lang.Override
    public RouteInfoResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RouteInfoResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RouteInfoResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RouteInfoResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.apache.rocketmq.proto.RouteInfoResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

