name: CodeSpell Check

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master

jobs:
  codespell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install CodeSpell
        run: pip install codespell==2.1.0

      - name: Run CodeSpell
        run: |
          codespell --quiet-level=2 \
                   --skip "./cpp/third_party,./style/codespell/ignore_words.txt,./.git" \
                   --ignore-words ./style/codespell/ignore_words.txt \
                   --exclude-file ./style/codespell/exclude_file.txt \