name: Check License Lines
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master
jobs:
  check-license-lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check License Lines
        uses: kt3k/license_checker@v1.0.6
