name: Node.js Build
on:
  workflow_call:
jobs:
  build:
    name: "${{ matrix.os }}, node-${{ matrix.nodejs }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        nodejs: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Node.js ${{ matrix.nodejs }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs }}

      - name: Build
        working-directory: ./nodejs
        run: npm i && npm run init && npm run build && npm pack
