name: Rust Coverage
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'rust/**'
  push:
    branches:
      - master
jobs:
  calculate-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install rust toolchain
        run: |
           rustup toolchain add --profile=minimal stable
           rustup override set stable

      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
      - name: Install cargo-llvm-cov
        run: |
          cargo install cargo-llvm-cov

      - name: Generate code coverage
        working-directory: ./rust
        run: cargo llvm-cov --all-features --workspace --ignore-filename-regex pb/ --codecov --output-path codecov.json

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          files: ./rust/codecov.json
          flags: rust
          verbose: true
          fail_ci_if_error: true
