name: Rust Coverage
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'rust/**'
  push:
    branches:
      - master
jobs:
  calculate-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov

      - name: Generate code coverage
        working-directory: ./rust
        run: cargo llvm-cov --all-features --workspace --ignore-filename-regex pb/ --codecov --output-path codecov.json

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          files: ./rust/codecov.json
          flags: rust
          verbose: true
          token: ${{ secrets.CODECOV_ACTION_KEY }}
          fail_ci_if_error: true
