name: Close Stale Issues/PRs

permissions:
  issues: write
  pull-requests: write

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 3
          exempt-issue-labels: "no stale,high priority"
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 30 days with no activity. It will be closed in 3 days if no further activity occurs."
          close-issue-message: "This issue was closed because it has been inactive for 3 days since being marked as stale."
          days-before-pr-stale: 30
          days-before-pr-close: 3
          exempt-pr-labels: "no stale,high priority"
          stale-pr-label: "stale"
          stale-pr-message: "This PR is stale because it has been open for 30 days with no activity. It will be closed in 3 days if no further activity occurs. If you wish not to mark it as stale, please leave a comment in this PR."
          close-pr-message: "This PR was closed because it has been inactive for 3 days since being marked as stale."
